### ISSUE TITLE
Write. Some. Tests.

### ISSUE THREAD

**Issue by ae-foster** [ae-foster/pyro#16]
There is a shocking lack of tests in the current module. Fortunately, the test cases already exist in `eig_estimation_benchmarking` and simply need to be ported / modified to become actual software tests. We could also review the state of tests for `glmm`

**Comment by eb8680** [comment]
@null-a porting the tests in `examples/contrib/oed/eig_estimation_benchmarking.py` into test cases in `tests/contrib/oed/` is another good task to pick up after #17 and #18 are resolved.

**Comment by null-a** [comment]
I started exploring this over [here](https://github.com/ae-foster/pyro/commits/oed-master-eig-tests).

**Comment by ae-foster** [comment]
Added some linear model tests to your branch @null-a : will finish off soon

**Comment by ae-foster** [comment]
We've now got linear model and finite space model tests ready for review ( #27 )
